import path from 'node:path';

const extensions: Record<string, string> = {
  '.c': 'c',
  '.cc': 'cpp',
  '.cpp': 'cpp',
  '.cxx': 'cpp',
  '.h': 'c',
  '.hpp': 'cpp',
  '.hxx': 'cpp',
  '.cs': 'csharp',
  '.css': 'css',
  '.scss': 'css',
  '.sass': 'css',
  '.less': 'css',
  '.clj': 'clojure',
  '.cljs': 'clojure',
  '.cljc': 'clojure',
  '.edn': 'clojure',
  '.dart': 'dart',
  '.el': 'elisp',
  '.elm': 'elm',
  '.erl': 'erlang',
  '.hrl': 'erlang',
  '.ex': 'elixir',
  '.exs': 'elixir',
  '.go': 'go',
  '.graphql': 'graphql',
  '.gql': 'graphql',
  '.hs': 'haskell',
  '.lhs': 'haskell',
  '.htm': 'html',
  '.html': 'html',
  '.java': 'java',
  '.js': 'javascript',
  '.jsx': 'javascript',
  '.cjs': 'javascript',
  '.mjs': 'javascript',
  '.jl': 'julia',
  '.json': 'json',
  '.json5': 'json',
  '.jsonc': 'json',
  '.kt': 'kotlin',
  '.kts': 'kotlin',
  '.lua': 'lua',
  '.md': 'markdown',
  '.mdx': 'markdown',
  '.m': 'objectivec',
  '.mm': 'objectivec',
  '.ml': 'ocaml',
  '.mli': 'ocaml',
  '.pl': 'perl',
  '.pm': 'perl',
  '.php': 'php',
  '.proto': 'protobuf',
  '.ps1': 'powershell',
  '.psm1': 'powershell',
  '.py': 'python',
  '.pyw': 'python',
  '.r': 'r',
  '.rmd': 'r',
  '.rb': 'ruby',
  '.rs': 'rust',
  '.ql': 'ql',
  '.res': 'rescript',
  '.scala': 'scala',
  '.sc': 'scala',
  '.sh': 'bash',
  '.bash': 'bash',
  '.zsh': 'bash',
  '.fish': 'bash',
  '.sol': 'solidity',
  '.sql': 'sql',
  '.swift': 'swift',
  '.tla': 'tlaplus',
  '.toml': 'toml',
  '.ts': 'typescript',
  '.tsx': 'typescript',
  '.cts': 'typescript',
  '.mts': 'typescript',
  '.xml': 'xml',
  '.svg': 'xml',
  '.yaml': 'yaml',
  '.yml': 'yaml',
  '.vue': 'vue',
  '.zig': 'zig',
  '.rdl': 'systemrdl',
  '.cmake': 'cmake'
};

export function detectLanguage(filePath: string): string {
  const name = path.basename(filePath).toLowerCase();
  if (name === 'dockerfile' || name === 'containerfile') return 'dockerfile';
  if (name === 'makefile' || name === 'gnumakefile') return 'makefile';
  if (name === 'cmakelists.txt') return 'cmake';
  if (name === '.gitignore' || name === '.dockerignore' || name === '.npmignore') return 'gitignore';
  if (name === 'cargo.toml') return 'toml';
  if (name === 'go.mod' || name === 'go.sum') return 'go';
  return extensions[path.extname(name)] ?? 'text';
}
