export { FileScanner } from './scanner/FileScanner.js';
export type { FileScannerOptions } from './scanner/FileScanner.js';
export { IgnoreMatcher, DEFAULT_EXCLUDES } from './scanner/IgnoreMatcher.js';
export type { IgnoreMatcherOptions } from './scanner/IgnoreMatcher.js';
export { detectLanguage } from './scanner/LanguageDetector.js';
export { IndexManager } from './core/IndexManager.js';
export { CodebaseIndexer } from './core/CodebaseIndexer.js';
export type { IndexManagerOptions, IndexUpdateResult } from './core/IndexManager.js';
export { IndexFormatError, IndexReader, IndexWriter } from './storage/BinaryIndex.js';
export { INDEX_FORMAT_VERSION } from './storage/IndexFormat.js';
export type { IndexMetadata, IndexSnapshot } from './storage/IndexFormat.js';
export type { SymbolKind, SymbolRecord } from './types/Symbol.js';
export type { RelationKind, RelationRecord } from './types/Relation.js';
export type { CodeChunk } from './types/CodeChunk.js';
export type { VectorRecord } from './types/VectorRecord.js';
export type { EmbeddingProvider } from './embeddings/EmbeddingProvider.js';
export { EmbeddingCache } from './embeddings/EmbeddingCache.js';
export { EmbeddingQueue } from './embeddings/EmbeddingQueue.js';
export { SemanticChunker } from './chunks/SemanticChunker.js';
export { ContextBuilder } from './context/ContextBuilder.js';
export type { CodeContext, ContextOptions } from './context/ContextBuilder.js';
export type { FileRecord, ScanError, ScanResult } from './types/FileRecord.js';